import { Search, X } from 'lucide-react'
import { useEffect, useRef } from 'react'

export type TemplateBooleanFilter = 'ALL' | 'TRUE' | 'FALSE'
type Props = { search: string; active: TemplateBooleanFilter; featured: TemplateBooleanFilter; onSearchChange: (value: string) => void; onActiveChange: (value: TemplateBooleanFilter) => void; onFeaturedChange: (value: TemplateBooleanFilter) => void }
const options = [{ value: 'ALL', label: 'Tất cả' }, { value: 'TRUE', label: 'Đang hoạt động' }, { value: 'FALSE', label: 'Ngừng hoạt động' }] as const
const featuredOptions = [{ value: 'ALL', label: 'Tất cả' }, { value: 'TRUE', label: 'Nổi bật' }, { value: 'FALSE', label: 'Không nổi bật' }] as const

export default function AdminCVTemplateFilters({ search, active, featured, onSearchChange, onActiveChange, onFeaturedChange }: Props) {
  const inputRef = useRef<HTMLInputElement>(null); const timer = useRef<number | null>(null)
  useEffect(() => { if (inputRef.current && inputRef.current.value !== search) inputRef.current.value = search }, [search])
  useEffect(() => () => { if (timer.current !== null) window.clearTimeout(timer.current) }, [])
  const schedule = (value: string) => { if (timer.current !== null) window.clearTimeout(timer.current); const normalized = value.trim(); if (normalized === search) return; timer.current = window.setTimeout(() => { timer.current = null; onSearchChange(normalized) }, 400) }
  const clear = () => { if (timer.current !== null) window.clearTimeout(timer.current); if (inputRef.current) inputRef.current.value = ''; onSearchChange('') }
  return <section className="mt-6 rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200 sm:p-5" aria-label="Tìm kiếm và lọc mẫu CV"><div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_220px_220px]"><label className="relative block"><span className="sr-only">Tìm mẫu CV</span><Search size={18} className="pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" /><input ref={inputRef} defaultValue={search} onChange={(event) => schedule(event.target.value)} placeholder="Tìm kiếm mẫu CV..." className="peer w-full rounded-xl border border-slate-300 py-3 pl-11 pr-11 text-sm text-slate-900 outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /><button type="button" onClick={clear} aria-label="Xóa từ khóa tìm kiếm" className="pointer-events-auto absolute right-2.5 top-1/2 inline-flex -translate-y-1/2 rounded-lg p-1.5 text-slate-400 hover:bg-slate-100 hover:text-slate-700 peer-placeholder-shown:pointer-events-none peer-placeholder-shown:opacity-0"><X size={16} /></button></label><label><span className="sr-only">Lọc trạng thái</span><select value={active} onChange={(event) => onActiveChange(event.target.value as TemplateBooleanFilter)} className="w-full rounded-xl border border-slate-300 bg-white px-3 py-3 text-sm font-medium text-slate-800 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100">{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label><label><span className="sr-only">Lọc trạng thái nổi bật</span><select value={featured} onChange={(event) => onFeaturedChange(event.target.value as TemplateBooleanFilter)} className="w-full rounded-xl border border-slate-300 bg-white px-3 py-3 text-sm font-medium text-slate-800 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100">{featuredOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label></div></section>
}
