import { ChevronDown, SlidersHorizontal, X } from 'lucide-react'
import { useId, useState } from 'react'
import { jobSortLabels, salaryFilterOptions, type SalaryFilter } from '../../config/jobSearchFilters'
import { EMPLOYMENT_TYPES, EXPERIENCE_REQUIREMENTS, INDUSTRIES, JOB_LEVELS, JOB_SORT_OPTIONS, WORK_MODES } from '../../types/job'
import type { EmploymentType, ExperienceRequirement, Industry, JobLevel, JobSortOption, WorkMode } from '../../types/job'
import { employmentLabel, experienceRequirementLabel, industryLabel, levelLabel, workModeLabel } from '../../utils/jobDisplay'

export type JobFilterValues = { employmentType: EmploymentType | ''; industry: Industry | ''; experienceRequirement: ExperienceRequirement | ''; level: JobLevel | ''; workMode: WorkMode | ''; salary: SalaryFilter; sort: JobSortOption }
type Props = { values: JobFilterValues; onChange: (values: JobFilterValues) => void; onClear: () => void }

const fieldClass = 'mt-1.5 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-800 outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100'

function Controls({ values, onChange, sidebar = false }: Pick<Props, 'values' | 'onChange'> & { sidebar?: boolean }) {
  const update = <K extends keyof JobFilterValues>(key: K, value: JobFilterValues[K]) => onChange({ ...values, [key]: value })
  return <div className={sidebar ? 'space-y-4' : 'grid gap-3 sm:grid-cols-2'}>
    <label className="block text-sm font-semibold text-slate-700">Ngành nghề<select value={values.industry} onChange={(event) => update('industry', event.target.value as Industry | '')} className={fieldClass}><option value="">Tất cả ngành nghề</option>{INDUSTRIES.map((value) => <option key={value} value={value}>{industryLabel(value)}</option>)}</select></label>
    <label className="block text-sm font-semibold text-slate-700">Kinh nghiệm<select value={values.experienceRequirement} onChange={(event) => update('experienceRequirement', event.target.value as ExperienceRequirement | '')} className={fieldClass}><option value="">Tất cả kinh nghiệm</option>{EXPERIENCE_REQUIREMENTS.map((value) => <option key={value} value={value}>{experienceRequirementLabel(value)}</option>)}</select></label>
    <label className="block text-sm font-semibold text-slate-700">Cấp bậc<select value={values.level} onChange={(event) => update('level', event.target.value as JobLevel | '')} className={fieldClass}><option value="">Tất cả cấp bậc</option>{JOB_LEVELS.map((value) => <option key={value} value={value}>{levelLabel(value)}</option>)}</select></label>
    <label className="block text-sm font-semibold text-slate-700">Hình thức làm việc<select value={values.workMode} onChange={(event) => update('workMode', event.target.value as WorkMode | '')} className={fieldClass}><option value="">Tất cả hình thức</option>{WORK_MODES.map((value) => <option key={value} value={value}>{workModeLabel(value)}</option>)}</select></label>
    <label className="block text-sm font-semibold text-slate-700">Mức lương<select value={values.salary} onChange={(event) => update('salary', event.target.value as SalaryFilter)} className={fieldClass}>{salaryFilterOptions.map(({ value, label }) => <option key={value || 'all'} value={value}>{label}</option>)}</select></label>
    <label className="block text-sm font-semibold text-slate-700">Loại công việc<select value={values.employmentType} onChange={(event) => update('employmentType', event.target.value as EmploymentType | '')} className={fieldClass}><option value="">Tất cả loại việc</option>{EMPLOYMENT_TYPES.map((value) => <option key={value} value={value}>{employmentLabel(value)}</option>)}</select></label>
    <label className="block text-sm font-semibold text-slate-700">Sắp xếp<select value={values.sort} onChange={(event) => update('sort', event.target.value as JobSortOption)} className={fieldClass}>{JOB_SORT_OPTIONS.map((value) => <option key={value} value={value}>{jobSortLabels[value]}</option>)}</select></label>
  </div>
}

export default function JobFilters({ values, onChange, onClear }: Props) {
  const [mobileOpen, setMobileOpen] = useState(false)
  const headingId = useId()
  const hasFilters = Object.entries(values).some(([key, value]) => key !== 'sort' && value !== '') || values.sort !== 'newest'
  return <>
    <section className="sticky top-6 hidden rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200 lg:block" aria-labelledby={headingId}><div className="mb-5 flex items-center justify-between gap-4"><div className="flex items-center gap-2 text-slate-950"><SlidersHorizontal size={18} className="text-blue-600" aria-hidden="true" /><h2 id={headingId} className="font-bold">Bộ lọc việc làm</h2></div>{hasFilters && <button type="button" onClick={onClear} className="inline-flex items-center gap-1 rounded-lg px-2 py-1 text-sm font-semibold text-slate-500 transition-colors hover:bg-slate-100 hover:text-blue-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500"><X size={15} aria-hidden="true" />Xóa tất cả</button>}</div><Controls values={values} onChange={onChange} sidebar /></section>
    <section className="lg:hidden"><button type="button" onClick={() => setMobileOpen(true)} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-800 shadow-sm transition-colors hover:bg-slate-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500"><SlidersHorizontal size={17} aria-hidden="true" />Bộ lọc{hasFilters && <span className="h-2 w-2 rounded-full bg-blue-600" aria-label="Đang có bộ lọc" />}</button></section>
    {mobileOpen && <div className="fixed inset-0 z-50 flex items-end bg-slate-950/40 p-3 sm:items-center sm:justify-center" role="presentation"><button type="button" className="absolute inset-0 cursor-default" aria-label="Đóng bộ lọc" onClick={() => setMobileOpen(false)} /><section role="dialog" aria-modal="true" aria-labelledby={`${headingId}-mobile`} className="relative max-h-[min(44rem,calc(100dvh-1.5rem))] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-5 shadow-xl"><div className="mb-5 flex items-center justify-between gap-4"><div><h2 id={`${headingId}-mobile`} className="text-lg font-bold text-slate-950">Bộ lọc việc làm</h2><p className="mt-1 text-sm text-slate-500">Chọn tiêu chí phù hợp với vị trí bạn đang tìm.</p></div><button type="button" onClick={() => setMobileOpen(false)} className="inline-flex h-10 w-10 items-center justify-center rounded-xl text-slate-500 transition-colors hover:bg-slate-100 hover:text-slate-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500" aria-label="Đóng bộ lọc"><X size={20} aria-hidden="true" /></button></div><Controls values={values} onChange={onChange} /><div className="mt-6 flex items-center justify-between gap-3 border-t border-slate-100 pt-4"><button type="button" onClick={() => { onClear(); setMobileOpen(false) }} className="rounded-xl px-3 py-2.5 text-sm font-semibold text-slate-600 transition-colors hover:bg-slate-100 hover:text-slate-900">Xóa bộ lọc</button><button type="button" onClick={() => setMobileOpen(false)} className="inline-flex items-center gap-1.5 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white transition-colors hover:bg-blue-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2">Xem kết quả<ChevronDown size={16} className="rotate-180" aria-hidden="true" /></button></div></section></div>}
  </>
}
