import { SlidersHorizontal, X } from 'lucide-react'
import { EMPLOYMENT_TYPES, EXPERIENCE_LEVELS, JOB_SORT_OPTIONS } from '../../types/job'
import type { EmploymentType, ExperienceLevel, JobSortOption } from '../../types/job'

export type JobFilterValues = { employmentType: EmploymentType | ''; experienceLevel: ExperienceLevel | ''; salary: string; sort: JobSortOption }
type JobFiltersProps = { values: JobFilterValues; onChange: (values: JobFilterValues) => void; onClear: () => void }

const employmentLabels: Record<EmploymentType, string> = { FULL_TIME: 'Toàn thời gian', PART_TIME: 'Bán thời gian', CONTRACT: 'Hợp đồng', INTERNSHIP: 'Thực tập', FREELANCE: 'Tự do' }
const experienceLabels: Record<ExperienceLevel, string> = { ENTRY: 'Mới bắt đầu', MID: 'Trung cấp', SENIOR: 'Cao cấp', LEAD: 'Trưởng nhóm', MANAGER: 'Quản lý' }
const sortLabels: Record<JobSortOption, string> = { newest: 'Mới đăng', oldest: 'Cũ nhất', salary_high: 'Lương cao nhất', salary_low: 'Lương thấp nhất' }

export default function JobFilters({ values, onChange, onClear }: JobFiltersProps) {
  const update = <K extends keyof JobFilterValues>(key: K, value: JobFilterValues[K]) => onChange({ ...values, [key]: value })
  return <aside className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200" aria-label="Bộ lọc việc làm"><div className="mb-5 flex items-center justify-between"><div className="flex items-center gap-2 text-slate-900"><SlidersHorizontal size={18} className="text-blue-600" /><h2 className="font-semibold">Bộ lọc</h2></div><button type="button" onClick={onClear} className="inline-flex items-center gap-1 text-xs font-semibold text-slate-500 hover:text-blue-600"><X size={14} />Xóa lọc</button></div><div className="space-y-4"><label className="block text-sm font-medium text-slate-700">Loại công việc<select value={values.employmentType} onChange={(event) => update('employmentType', event.target.value as EmploymentType | '')} className="mt-1.5 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-700 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100"><option value="">Tất cả loại việc</option>{EMPLOYMENT_TYPES.map((type) => <option key={type} value={type}>{employmentLabels[type]}</option>)}</select></label><label className="block text-sm font-medium text-slate-700">Kinh nghiệm<select value={values.experienceLevel} onChange={(event) => update('experienceLevel', event.target.value as ExperienceLevel | '')} className="mt-1.5 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-700 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100"><option value="">Tất cả cấp độ</option>{EXPERIENCE_LEVELS.map((level) => <option key={level} value={level}>{experienceLabels[level]}</option>)}</select></label><label className="block text-sm font-medium text-slate-700">Mức lương<select value={values.salary} onChange={(event) => update('salary', event.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-700 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100"><option value="">Tất cả mức lương</option><option value="0-10000000">Dưới 10 triệu</option><option value="10000000-20000000">10 – 20 triệu</option><option value="20000000-30000000">20 – 30 triệu</option><option value="30000000-">Từ 30 triệu</option></select></label><label className="block text-sm font-medium text-slate-700">Sắp xếp<select value={values.sort} onChange={(event) => update('sort', event.target.value as JobSortOption)} className="mt-1.5 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-700 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100">{JOB_SORT_OPTIONS.map((sort) => <option key={sort} value={sort}>{sortLabels[sort]}</option>)}</select></label></div></aside>
}
