import { Plus, Trash2 } from 'lucide-react'
import { useState } from 'react'
import type { CVCreateRequest, CVCertificateItem, CVEducationItem, CVExperienceItem, CVLanguageItem, CVLanguageProficiency, CVPersonalInfo, CVProjectItem, CVSkillItem, CVSkillLevel, CVTemplate } from '../../types/cv'
import CVPreview from './CVPreview'

type Props = { initial: CVCreateRequest; submitLabel: string; submitting: boolean; onSubmit: (data: CVCreateRequest) => Promise<void>; onCancel: () => void; template?: CVTemplate }
const input = 'mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100'
const label = 'block text-xs font-semibold text-slate-700'
const selectOptions = (values: string[]) => values.map((value) => <option key={value} value={value}>{value}</option>)

function Block({ title, children, onAdd, addLabel }: { title: string; children: React.ReactNode; onAdd?: () => void; addLabel?: string }) {
  return <section className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between gap-4"><h2 className="font-bold text-slate-900">{title}</h2>{onAdd && <button type="button" onClick={onAdd} className="inline-flex items-center gap-1 text-xs font-semibold text-blue-700 hover:text-blue-800"><Plus size={15} />{addLabel}</button>}</div><div className="mt-4 space-y-4">{children}</div></section>
}

export default function CVForm({ initial, submitLabel, submitting, onSubmit, onCancel, template = 'modern' }: Props) {
  const [data, setData] = useState<CVCreateRequest>(initial)
  const [showPreview, setShowPreview] = useState(false)
  const updateInfo = (key: keyof CVPersonalInfo, value: string) => setData((current) => ({ ...current, personal_info: { ...current.personal_info, [key]: value || null } }))
  const submit = async (event: React.FormEvent) => { event.preventDefault(); await onSubmit(data) }
  const remove = <T,>(items: T[], index: number) => items.filter((_, itemIndex) => itemIndex !== index)

  return <form onSubmit={submit} className="grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(330px,0.85fr)]"><div className="space-y-5">
    <Block title="Thông tin CV"><label className={label}>Tên CV<input required maxLength={255} value={data.title} onChange={(e) => setData({ ...data, title: e.target.value })} className={input} placeholder="CV Backend Developer" /></label><p className="text-xs text-slate-500">Đặt tên để phân biệt khi bạn có nhiều CV.</p></Block>
    <Block title="Thông tin cá nhân"><div className="grid gap-3 sm:grid-cols-2">{([['full_name','Họ và tên','text'],['email','Email','email'],['phone','Số điện thoại','tel'],['address','Địa chỉ','text'],['date_of_birth','Ngày sinh','date'],['linkedin_url','LinkedIn','url'],['github_url','GitHub','url'],['portfolio_url','Portfolio','url']] as const).map(([key, text, type]) => <label key={key} className={label}>{text}<input type={type} value={data.personal_info[key] ?? ''} onChange={(e) => updateInfo(key, e.target.value)} className={input} /></label>)}</div></Block>
    <Block title="Mục tiêu nghề nghiệp"><textarea maxLength={5000} value={data.career_objective ?? ''} onChange={(e) => setData({ ...data, career_objective: e.target.value || null })} className={`${input} min-h-28 resize-y`} placeholder="Mô tả ngắn gọn mục tiêu của bạn." /><p className="text-right text-xs text-slate-400">{(data.career_objective ?? '').length}/5000</p></Block>
    <Block title="Học vấn" onAdd={() => setData({ ...data, educations: [...data.educations, { school_name: '', is_current: false }] })} addLabel="Thêm học vấn">{data.educations.map((item, i) => <Item key={i} onRemove={() => setData({ ...data, educations: remove(data.educations, i) })}><div className="grid gap-3 sm:grid-cols-2"><Field label="Trường" value={item.school_name} required onChange={(v) => updateEducation(i, { school_name: v })} /><Field label="Bằng cấp" value={item.degree} onChange={(v) => updateEducation(i, { degree: v || null })} /><Field label="Chuyên ngành" value={item.field_of_study} onChange={(v) => updateEducation(i, { field_of_study: v || null })} /><Dates item={item} onChange={(patch) => updateEducation(i, patch)} /><TextArea value={item.description} onChange={(v) => updateEducation(i, { description: v || null })} /></div></Item>)}</Block>
    <Block title="Kinh nghiệm" onAdd={() => setData({ ...data, experiences: [...data.experiences, { company_name: '', position: '', is_current: false }] })} addLabel="Thêm kinh nghiệm">{data.experiences.map((item, i) => <Item key={i} onRemove={() => setData({ ...data, experiences: remove(data.experiences, i) })}><div className="grid gap-3 sm:grid-cols-2"><Field label="Công ty" value={item.company_name} required onChange={(v) => updateExperience(i, { company_name: v })} /><Field label="Vị trí" value={item.position} required onChange={(v) => updateExperience(i, { position: v })} /><Dates item={item} onChange={(patch) => updateExperience(i, patch)} /><TextArea value={item.description} onChange={(v) => updateExperience(i, { description: v || null })} /></div></Item>)}</Block>
    <Block title="Kỹ năng" onAdd={() => setData({ ...data, skills: [...data.skills, { name: '', level: null }] })} addLabel="Thêm kỹ năng">{data.skills.map((item, i) => <Item key={i} onRemove={() => setData({ ...data, skills: remove(data.skills, i) })}><div className="grid gap-3 sm:grid-cols-2"><Field label="Kỹ năng" value={item.name} required onChange={(v) => updateSkill(i, { name: v })} /><label className={label}>Cấp độ<select value={item.level ?? ''} onChange={(e) => updateSkill(i, { level: e.target.value ? e.target.value as CVSkillLevel : null })} className={input}><option value="">Chưa chọn</option>{selectOptions(['BEGINNER','INTERMEDIATE','ADVANCED','EXPERT'])}</select></label></div></Item>)}</Block>
    <Block title="Dự án" onAdd={() => setData({ ...data, projects: [...data.projects, { name: '', technologies: [] }] })} addLabel="Thêm dự án">{data.projects.map((item, i) => <Item key={i} onRemove={() => setData({ ...data, projects: remove(data.projects, i) })}><div className="grid gap-3 sm:grid-cols-2"><Field label="Tên dự án" value={item.name} required onChange={(v) => updateProject(i, { name: v })} /><Field label="Vai trò" value={item.role} onChange={(v) => updateProject(i, { role: v || null })} /><Field label="Bắt đầu" type="date" value={item.start_date} onChange={(v) => updateProject(i, { start_date: v || null })} /><Field label="Kết thúc" type="date" value={item.end_date} onChange={(v) => updateProject(i, { end_date: v || null })} /><Field label="Công nghệ (phân cách dấu phẩy)" value={item.technologies.join(', ')} onChange={(v) => updateProject(i, { technologies: v.split(',').map((x) => x.trim()).filter(Boolean) })} /><Field label="Project URL" type="url" value={item.project_url} onChange={(v) => updateProject(i, { project_url: v || null })} /><TextArea value={item.description} onChange={(v) => updateProject(i, { description: v || null })} /></div></Item>)}</Block>
    <Block title="Chứng chỉ" onAdd={() => setData({ ...data, certificates: [...data.certificates, { name: '' }] })} addLabel="Thêm chứng chỉ">{data.certificates.map((item, i) => <Item key={i} onRemove={() => setData({ ...data, certificates: remove(data.certificates, i) })}><div className="grid gap-3 sm:grid-cols-2"><Field label="Tên chứng chỉ" value={item.name} required onChange={(v) => updateCertificate(i, { name: v })} /><Field label="Tổ chức" value={item.organization} onChange={(v) => updateCertificate(i, { organization: v || null })} /><Field label="Ngày cấp" type="date" value={item.issue_date} onChange={(v) => updateCertificate(i, { issue_date: v || null })} /><Field label="Ngày hết hạn" type="date" value={item.expiration_date} onChange={(v) => updateCertificate(i, { expiration_date: v || null })} /><Field label="Credential URL" type="url" value={item.credential_url} onChange={(v) => updateCertificate(i, { credential_url: v || null })} /></div></Item>)}</Block>
    <Block title="Ngoại ngữ" onAdd={() => setData({ ...data, languages: [...data.languages, { name: '', proficiency: null }] })} addLabel="Thêm ngoại ngữ">{data.languages.map((item, i) => <Item key={i} onRemove={() => setData({ ...data, languages: remove(data.languages, i) })}><div className="grid gap-3 sm:grid-cols-2"><Field label="Ngôn ngữ" value={item.name} required onChange={(v) => updateLanguage(i, { name: v })} /><label className={label}>Trình độ<select value={item.proficiency ?? ''} onChange={(e) => updateLanguage(i, { proficiency: e.target.value ? e.target.value as CVLanguageProficiency : null })} className={input}><option value="">Chưa chọn</option>{selectOptions(['BASIC','CONVERSATIONAL','PROFESSIONAL','FLUENT','NATIVE'])}</select></label></div></Item>)}</Block>
    <div className="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" onClick={onCancel} className="rounded-lg px-4 py-2.5 text-sm font-semibold text-slate-600 hover:bg-slate-100">Huỷ</button><button disabled={submitting} className="rounded-lg bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-60">{submitting ? 'Đang lưu...' : submitLabel}</button></div>
  </div><aside className="hidden xl:block"><div className="sticky top-24"><p className="mb-3 text-sm font-bold text-slate-700">Xem trước CV</p><CVPreview cv={data} template={template} /></div></aside><button type="button" onClick={() => setShowPreview(!showPreview)} className="fixed bottom-4 right-4 z-30 rounded-full bg-slate-900 px-4 py-3 text-sm font-semibold text-white shadow-lg xl:hidden">{showPreview ? 'Đóng xem trước' : 'Xem trước CV'}</button>{showPreview && <div className="fixed inset-0 z-20 overflow-y-auto bg-slate-950/40 p-4 pt-20 xl:hidden"><CVPreview cv={data} template={template} /></div>}</form>

  function updateEducation(index: number, patch: Partial<CVEducationItem>) { setData((current) => ({ ...current, educations: current.educations.map((item, i) => i === index ? { ...item, ...patch } : item) })) }
  function updateExperience(index: number, patch: Partial<CVExperienceItem>) { setData((current) => ({ ...current, experiences: current.experiences.map((item, i) => i === index ? { ...item, ...patch } : item) })) }
  function updateSkill(index: number, patch: Partial<CVSkillItem>) { setData((current) => ({ ...current, skills: current.skills.map((item, i) => i === index ? { ...item, ...patch } : item) })) }
  function updateProject(index: number, patch: Partial<CVProjectItem>) { setData((current) => ({ ...current, projects: current.projects.map((item, i) => i === index ? { ...item, ...patch } : item) })) }
  function updateCertificate(index: number, patch: Partial<CVCertificateItem>) { setData((current) => ({ ...current, certificates: current.certificates.map((item, i) => i === index ? { ...item, ...patch } : item) })) }
  function updateLanguage(index: number, patch: Partial<CVLanguageItem>) { setData((current) => ({ ...current, languages: current.languages.map((item, i) => i === index ? { ...item, ...patch } : item) })) }
}

function Item({ children, onRemove }: { children: React.ReactNode; onRemove: () => void }) { return <div className="rounded-lg border border-slate-200 p-4"><div className="mb-3 flex justify-end"><button type="button" onClick={onRemove} className="inline-flex items-center gap-1 text-xs font-semibold text-red-600 hover:text-red-700"><Trash2 size={14} />Xoá</button></div>{children}</div> }
function Field({ label: text, value, onChange, type = 'text', required = false }: { label: string; value?: string | null; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label className={label}>{text}<input type={type} required={required} value={value ?? ''} onChange={(e) => onChange(e.target.value)} className={input} /></label> }
function TextArea({ value, onChange }: { value?: string | null; onChange: (value: string) => void }) { return <label className={`${label} sm:col-span-2`}>Mô tả<textarea value={value ?? ''} onChange={(e) => onChange(e.target.value)} className={`${input} min-h-20 resize-y`} /></label> }
function Dates<T extends { start_date?: string | null; end_date?: string | null; is_current: boolean }>({ item, onChange }: { item: T; onChange: (patch: Partial<T>) => void }) { return <div className="grid gap-3 sm:col-span-2 sm:grid-cols-3"><Field label="Bắt đầu" type="date" value={item.start_date} onChange={(v) => onChange({ start_date: v || null } as Partial<T>)} /><Field label="Kết thúc" type="date" value={item.end_date} onChange={(v) => onChange({ end_date: v || null } as Partial<T>)} /><label className={`${label} flex items-end gap-2 pb-2`}><input type="checkbox" checked={item.is_current} onChange={(e) => onChange({ is_current: e.target.checked, end_date: e.target.checked ? null : item.end_date } as Partial<T>)} />Đang diễn ra</label></div> }
