import { ArrowRight, CalendarClock, Eye, FileText, Star } from 'lucide-react'
import { Link } from 'react-router-dom'
import type { AdminAuditCVListItem } from '../../../types/adminAudit'
import { formatJobTimestamp } from '../../../utils/jobDisplay'
import AdminUserAvatar from '../users/AdminUserAvatar'

type Props = { cvs: AdminAuditCVListItem[]; returnTo: string }

export default function AdminCVList({ cvs, returnTo }: Props) {
  return (
    <section className="mt-6" aria-label="Danh sách CV ứng viên">
      <div className="hidden overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200 md:block"><table className="w-full table-fixed text-left"><thead className="border-b border-slate-200 bg-slate-50 text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th className="w-[26%] px-5 py-4">CV</th><th className="w-[27%] px-4 py-4">Ứng viên</th><th className="w-[22%] px-4 py-4">Mẫu CV</th><th className="w-[16%] px-4 py-4">Cập nhật</th><th className="w-[9%] px-5 py-4 text-right"><span className="sr-only">Xem chi tiết</span></th></tr></thead><tbody className="divide-y divide-slate-100">{cvs.map((cv) => <tr key={cv.id} className="transition-colors hover:bg-slate-50/80"><td className="px-5 py-4"><Link to={`/admin/cvs/${cv.id}`} state={{ returnTo }} className="inline-flex max-w-full items-center gap-2 font-semibold text-slate-950 hover:text-blue-700"><FileText size={17} className="shrink-0 text-blue-600" aria-hidden="true" /><span className="truncate" title={cv.title}>{cv.title}</span></Link>{cv.is_default && <span className="mt-2 inline-flex items-center gap-1 rounded-full bg-amber-50 px-2 py-1 text-xs font-bold text-amber-800 ring-1 ring-inset ring-amber-200"><Star size={12} aria-hidden="true" />Mặc định</span>}</td><td className="px-4 py-4"><div className="flex min-w-0 items-center gap-3"><AdminUserAvatar name={cv.candidate.full_name} url={cv.candidate.avatar_url} /><div className="min-w-0"><Link to={`/admin/users/${cv.candidate_id}`} className="block truncate font-semibold text-slate-900 hover:text-blue-700" title={cv.candidate.full_name}>{cv.candidate.full_name}</Link><p className="mt-1 truncate text-sm text-slate-500">{cv.candidate.email}</p></div></div></td><td className="px-4 py-4"><p className="truncate font-medium text-slate-800" title={cv.template.name}>{cv.template.name}</p><p className="mt-1 text-xs text-slate-500">{cv.template.is_active ? 'Đang hoạt động' : 'Ngừng hoạt động'}</p></td><td className="px-4 py-4 text-sm text-slate-600"><span className="inline-flex items-start gap-1.5"><CalendarClock size={15} className="mt-0.5 shrink-0 text-slate-400" aria-hidden="true" />{formatJobTimestamp(cv.updated_at)}</span></td><td className="px-5 py-4 text-right"><Link to={`/admin/cvs/${cv.id}`} state={{ returnTo }} className="inline-flex items-center gap-1.5 rounded-lg px-2.5 py-2 text-sm font-semibold text-blue-700 hover:bg-blue-50"><Eye size={16} aria-hidden="true" />Chi tiết</Link></td></tr>)}</tbody></table></div>
      <div className="space-y-3 md:hidden">{cvs.map((cv) => <article key={cv.id} className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-blue-700"><FileText size={19} aria-hidden="true" /></span><div className="min-w-0 flex-1"><Link to={`/admin/cvs/${cv.id}`} state={{ returnTo }} className="block break-words font-bold text-slate-950 hover:text-blue-700">{cv.title}</Link><p className="mt-1 break-words text-sm text-slate-500">{cv.template.name}</p></div>{cv.is_default && <Star size={17} className="shrink-0 text-amber-500" aria-label="CV mặc định" />}</div><div className="mt-4 flex items-center gap-3 border-t border-slate-100 pt-4"><AdminUserAvatar name={cv.candidate.full_name} url={cv.candidate.avatar_url} /><Link to={`/admin/users/${cv.candidate_id}`} className="min-w-0 truncate text-sm font-semibold text-slate-800 hover:text-blue-700">{cv.candidate.full_name}</Link></div><div className="mt-4 flex items-center justify-between gap-3"><span className="text-xs text-slate-500">Cập nhật {formatJobTimestamp(cv.updated_at)}</span><Link to={`/admin/cvs/${cv.id}`} state={{ returnTo }} className="inline-flex shrink-0 items-center gap-1 text-sm font-semibold text-blue-700">Chi tiết<ArrowRight size={15} aria-hidden="true" /></Link></div></article>)}</div>
    </section>
  )
}
