import { ArrowRight, CalendarClock, Eye, FileText, Mail } from 'lucide-react'
import { Link } from 'react-router-dom'
import type { AdminAuditApplicationListItem } from '../../../types/adminAudit'
import { formatJobTimestamp } from '../../../utils/jobDisplay'
import AdminUserAvatar from '../users/AdminUserAvatar'
import AdminApplicationStatusBadge from './AdminApplicationStatusBadge'

type Props = { applications: AdminAuditApplicationListItem[]; returnTo: string }

export default function AdminApplicationList({ applications, returnTo }: Props) {
  return (
    <section className="mt-6" aria-label="Danh sách đơn ứng tuyển">
      <div className="hidden overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200 lg:block">
        <table className="w-full table-fixed text-left">
          <thead className="border-b border-slate-200 bg-slate-50 text-xs font-bold uppercase tracking-wide text-slate-500"><tr><th className="w-[25%] px-5 py-4">Ứng viên</th><th className="w-[28%] px-4 py-4">Công việc</th><th className="w-[18%] px-4 py-4">CV</th><th className="w-[16%] px-4 py-4">Trạng thái</th><th className="w-[13%] px-5 py-4 text-right">Cập nhật</th></tr></thead>
          <tbody className="divide-y divide-slate-100">{applications.map((application) => <tr key={application.id} className="transition-colors hover:bg-slate-50/80"><td className="px-5 py-4"><div className="flex min-w-0 items-center gap-3"><AdminUserAvatar name={application.candidate.full_name} url={application.candidate.avatar_url} /><div className="min-w-0"><Link to={`/admin/users/${application.candidate_id}`} className="block truncate font-semibold text-slate-950 hover:text-blue-700" title={application.candidate.full_name}>{application.candidate.full_name}</Link><p className="mt-1 truncate text-sm text-slate-500" title={application.candidate.email}>{application.candidate.email}</p></div></div></td><td className="px-4 py-4"><Link to={`/admin/jobs/${application.job_id}`} className="block truncate font-semibold text-slate-900 hover:text-blue-700" title={application.job.title}>{application.job.title}</Link><p className="mt-1 truncate text-sm text-slate-500" title={application.job.company_name}>{application.job.company_name}</p></td><td className="px-4 py-4"><Link to={`/admin/cvs/${application.cv_id}`} state={{ returnTo }} className="inline-flex max-w-full items-center gap-1.5 truncate text-sm font-semibold text-blue-700 hover:text-blue-900"><FileText size={15} className="shrink-0" aria-hidden="true" /><span className="truncate" title={application.cv.title}>{application.cv.title}</span></Link><p className="mt-1 truncate text-xs text-slate-500" title={application.cv.template.name}>{application.cv.template.name}</p></td><td className="px-4 py-4"><AdminApplicationStatusBadge status={application.status} /></td><td className="px-5 py-4 text-right text-xs text-slate-500"><span className="inline-flex items-start gap-1.5 text-left"><CalendarClock size={14} className="mt-0.5 shrink-0 text-slate-400" aria-hidden="true" />{formatJobTimestamp(application.updated_at)}</span><Link to={`/admin/applications/${application.id}`} state={{ returnTo }} className="mt-2 inline-flex items-center gap-1 text-sm font-semibold text-blue-700 hover:text-blue-900">Chi tiết<Eye size={15} aria-hidden="true" /></Link></td></tr>)}</tbody>
        </table>
      </div>
      <div className="space-y-3 lg:hidden">{applications.map((application) => <article key={application.id} className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><Link to={`/admin/jobs/${application.job_id}`} className="block break-words text-base font-bold text-slate-950 hover:text-blue-700">{application.job.title}</Link><p className="mt-1 break-words text-sm text-slate-600">{application.job.company_name}</p></div><AdminApplicationStatusBadge status={application.status} /></div><div className="mt-4 flex items-center gap-3 border-y border-slate-100 py-3"><AdminUserAvatar name={application.candidate.full_name} url={application.candidate.avatar_url} /><div className="min-w-0"><Link to={`/admin/users/${application.candidate_id}`} className="block truncate text-sm font-semibold text-slate-900 hover:text-blue-700">{application.candidate.full_name}</Link><p className="mt-0.5 flex items-center gap-1 truncate text-xs text-slate-500"><Mail size={13} aria-hidden="true" />{application.candidate.email}</p></div></div><Link to={`/admin/applications/${application.id}`} state={{ returnTo }} className="mt-4 inline-flex items-center gap-1.5 text-sm font-semibold text-blue-700 hover:text-blue-900">Xem chi tiết đơn<ArrowRight size={16} aria-hidden="true" /></Link></article>)}</div>
    </section>
  )
}
