import { CircleDollarSign, FileText, LoaderCircle, Save, Sparkles } from 'lucide-react'
import { useState } from 'react'
import type { FormEvent } from 'react'
import type { JobCreateRequest, RecruiterJob, SalaryType } from '../../types/job'

type Props = { initialJob?: RecruiterJob; submitting: boolean; serverError: string | null; submitLabel: string; onSubmit: (payload: JobCreateRequest) => Promise<void>; onCancel: () => void }
type FormState = { title: string; company_name: string; industry: string; level: string; experience_requirement: string; employment_type: string; work_mode: string; vacancies: string; location: string; salary_type: SalaryType; salary_min: string; salary_max: string; salary_fixed: string; description: string; requirements: string; benefits: string; skills: string }

const industryOptions = [['INFORMATION_TECHNOLOGY', 'Công nghệ thông tin'], ['FINANCE_BANKING', 'Tài chính – Ngân hàng'], ['MARKETING_ADVERTISING', 'Marketing – Quảng cáo'], ['SALES', 'Kinh doanh – Bán hàng'], ['HUMAN_RESOURCES', 'Nhân sự'], ['EDUCATION', 'Giáo dục'], ['HEALTHCARE', 'Y tế'], ['MANUFACTURING', 'Sản xuất'], ['LOGISTICS', 'Logistics'], ['OTHER', 'Khác']]
const levelOptions = [['INTERN', 'Thực tập sinh'], ['JUNIOR', 'Junior'], ['STAFF', 'Nhân viên'], ['SENIOR', 'Senior'], ['LEAD', 'Lead'], ['MANAGER', 'Quản lý']]
const experienceOptions = [['NO_EXPERIENCE', 'Chưa có kinh nghiệm'], ['LESS_THAN_ONE_YEAR', 'Dưới 1 năm'], ['ONE_TO_THREE_YEARS', '1–3 năm'], ['THREE_TO_FIVE_YEARS', '3–5 năm'], ['MORE_THAN_FIVE_YEARS', 'Trên 5 năm']]
const employmentOptions = [['FULL_TIME', 'Toàn thời gian'], ['PART_TIME', 'Bán thời gian'], ['CONTRACT', 'Hợp đồng'], ['INTERNSHIP', 'Thực tập'], ['FREELANCE', 'Freelance']]
const workOptions = [['ONSITE', 'Tại văn phòng'], ['HYBRID', 'Hybrid'], ['REMOTE', 'Từ xa']]
const inputClass = 'mt-2 w-full rounded-xl border border-slate-300 bg-white px-3.5 py-2.5 text-sm text-slate-900 outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100 disabled:bg-slate-100'
const labelClass = 'text-sm font-semibold text-slate-700'

function initialState(job?: RecruiterJob): FormState {
  return { title: job?.title ?? '', company_name: job?.company_name ?? '', industry: job?.industry ?? '', level: job?.level ?? '', experience_requirement: job?.experience_requirement ?? '', employment_type: job?.employment_type ?? '', work_mode: job?.work_mode ?? '', vacancies: String(job?.vacancies ?? 1), location: job?.location ?? '', salary_type: job?.salary_type ?? 'NEGOTIABLE', salary_min: job?.salary_min?.toString() ?? '', salary_max: job?.salary_max?.toString() ?? '', salary_fixed: job?.salary_fixed?.toString() ?? '', description: job?.description ?? '', requirements: job?.requirements ?? '', benefits: job?.benefits ?? '', skills: job?.skills?.join(', ') ?? '' }
}

export default function RecruiterJobForm({ initialJob, submitting, serverError, submitLabel, onSubmit, onCancel }: Props) {
  const [form, setForm] = useState<FormState>(() => initialState(initialJob))
  const [formError, setFormError] = useState<string | null>(null)
  const set = (field: keyof FormState, value: string) => setForm((current) => ({ ...current, [field]: value }))
  const changeSalaryType = (value: SalaryType) => setForm((current) => ({ ...current, salary_type: value, salary_min: '', salary_max: '', salary_fixed: '' }))
  const handleSubmit = async (event: FormEvent) => {
    event.preventDefault(); setFormError(null)
    const min = form.salary_min ? Number(form.salary_min) : null; const max = form.salary_max ? Number(form.salary_max) : null; const fixed = form.salary_fixed ? Number(form.salary_fixed) : null
    if (form.salary_type === 'RANGE' && (min === null || max === null || min < 1 || max < min)) { setFormError('Khoảng lương phải lớn hơn 0 và mức tối đa không được thấp hơn mức tối thiểu.'); return }
    if (form.salary_type === 'FIXED' && (fixed === null || fixed < 1)) { setFormError('Vui lòng nhập mức lương cố định lớn hơn 0.'); return }
    await onSubmit({ title: form.title.trim(), company_name: form.company_name.trim(), industry: form.industry ? form.industry as JobCreateRequest['industry'] : null, level: form.level ? form.level as JobCreateRequest['level'] : null, experience_requirement: form.experience_requirement ? form.experience_requirement as JobCreateRequest['experience_requirement'] : null, employment_type: form.employment_type ? form.employment_type as JobCreateRequest['employment_type'] : null, work_mode: form.work_mode ? form.work_mode as JobCreateRequest['work_mode'] : null, vacancies: Number(form.vacancies), location: form.location.trim() || null, salary_type: form.salary_type, salary_min: form.salary_type === 'RANGE' ? min : null, salary_max: form.salary_type === 'RANGE' ? max : null, salary_fixed: form.salary_type === 'FIXED' ? fixed : null, salary_currency: 'VND', description: form.description.trim(), requirements: form.requirements.trim(), benefits: form.benefits.trim() || null, skills: form.skills.split(',').map((skill) => skill.trim()).filter(Boolean) })
  }
  const select = (label: string, field: keyof FormState, options: string[][]) => <label className={labelClass}>{label}<select value={form[field]} onChange={(e) => set(field, e.target.value)} className={inputClass}><option value="">Chọn {label.toLowerCase()}</option>{options.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label>

  return <form onSubmit={handleSubmit} className="space-y-6">
    {(formError || serverError) && <div role="alert" className="rounded-xl bg-red-50 px-4 py-3 text-sm font-medium text-red-700 ring-1 ring-red-100">{formError || serverError}</div>}
    <section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-blue-700"><FileText size={20} /></span><div><h2 className="font-bold text-slate-900">Thông tin công việc</h2><p className="text-sm text-slate-500">Những thông tin ứng viên nhìn thấy đầu tiên.</p></div></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className={`${labelClass} sm:col-span-2`}>Tiêu đề công việc *<input required maxLength={255} value={form.title} onChange={(e) => set('title', e.target.value)} className={inputClass} placeholder="Ví dụ: Senior Frontend Developer" /></label><label className={labelClass}>Tên công ty *<input required maxLength={255} value={form.company_name} onChange={(e) => set('company_name', e.target.value)} className={inputClass} /></label>{select('Ngành nghề', 'industry', industryOptions)}{select('Cấp bậc', 'level', levelOptions)}{select('Kinh nghiệm', 'experience_requirement', experienceOptions)}{select('Hình thức làm việc', 'employment_type', employmentOptions)}{select('Cách thức làm việc', 'work_mode', workOptions)}<label className={labelClass}>Số lượng cần tuyển *<input required type="number" min="1" value={form.vacancies} onChange={(e) => set('vacancies', e.target.value)} className={inputClass} /></label><label className={labelClass}>Địa điểm<input maxLength={255} value={form.location} onChange={(e) => set('location', e.target.value)} className={inputClass} placeholder="Quận, thành phố" /></label></div></section>
    <section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700"><CircleDollarSign size={21} /></span><div><h2 className="font-bold text-slate-900">Mức lương</h2><p className="text-sm text-slate-500">Đơn vị tiền tệ mặc định: VND.</p></div></div><fieldset className="mt-6"><legend className={labelClass}>Loại lương *</legend><div className="mt-3 grid gap-3 sm:grid-cols-3">{([['RANGE', 'Khoảng lương'], ['FIXED', 'Lương cố định'], ['NEGOTIABLE', 'Thỏa thuận']] as const).map(([value, label]) => <label key={value} className={`cursor-pointer rounded-xl border p-3 text-sm font-semibold transition ${form.salary_type === value ? 'border-blue-500 bg-blue-50 text-blue-700 ring-2 ring-blue-100' : 'border-slate-200 text-slate-600 hover:border-slate-300'}`}><input type="radio" name="salary_type" value={value} checked={form.salary_type === value} onChange={() => changeSalaryType(value)} className="mr-2 accent-blue-600" />{label}</label>)}</div></fieldset>{form.salary_type === 'RANGE' && <div className="mt-5 grid gap-5 sm:grid-cols-2"><label className={labelClass}>Từ *<input required type="number" min="1" value={form.salary_min} onChange={(e) => set('salary_min', e.target.value)} className={inputClass} placeholder="15.000.000" /></label><label className={labelClass}>Đến *<input required type="number" min="1" value={form.salary_max} onChange={(e) => set('salary_max', e.target.value)} className={inputClass} placeholder="25.000.000" /></label></div>}{form.salary_type === 'FIXED' && <label className={`${labelClass} mt-5 block max-w-sm`}>Mức lương *<input required type="number" min="1" value={form.salary_fixed} onChange={(e) => set('salary_fixed', e.target.value)} className={inputClass} /></label>}{form.salary_type === 'NEGOTIABLE' && <p className="mt-5 rounded-xl bg-slate-50 px-4 py-3 text-sm text-slate-600">Tin tuyển dụng sẽ hiển thị mức lương “Thỏa thuận”.</p>}</section>
    <section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-50 text-amber-700"><Sparkles size={20} /></span><div><h2 className="font-bold text-slate-900">Nội dung tuyển dụng</h2><p className="text-sm text-slate-500">Viết rõ ràng, cụ thể và dễ quét.</p></div></div><div className="mt-6 space-y-5"><label className={`${labelClass} block`}>Mô tả công việc *<textarea required rows={6} value={form.description} onChange={(e) => set('description', e.target.value)} className={inputClass} /></label><label className={`${labelClass} block`}>Yêu cầu ứng viên *<textarea required rows={5} value={form.requirements} onChange={(e) => set('requirements', e.target.value)} className={inputClass} /></label><label className={`${labelClass} block`}>Quyền lợi<textarea rows={5} value={form.benefits} onChange={(e) => set('benefits', e.target.value)} className={inputClass} /></label><label className={`${labelClass} block`}>Kỹ năng<input value={form.skills} onChange={(e) => set('skills', e.target.value)} className={inputClass} placeholder="React, TypeScript, Tailwind CSS" /><span className="mt-1.5 block text-xs font-normal text-slate-500">Phân cách các kỹ năng bằng dấu phẩy.</span></label></div></section>
    <div className="sticky bottom-4 flex flex-col-reverse gap-3 rounded-2xl bg-white/95 p-4 shadow-lg shadow-slate-300/40 ring-1 ring-slate-200 backdrop-blur sm:flex-row sm:justify-end"><button type="button" onClick={onCancel} disabled={submitting} className="rounded-xl border border-slate-300 px-5 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50 disabled:opacity-50">Hủy</button><button type="submit" disabled={submitting} className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-60">{submitting ? <LoaderCircle size={17} className="animate-spin" /> : <Save size={17} />}{submitting ? 'Đang lưu...' : submitLabel}</button></div>
  </form>
}
